### ISSUE TITLE
Problems to build with meson

### ISSUE THREAD

**Issue by RLFontan** [Philip-Scott/wallpaperize#14]
Hey guys, here is the deal:

I used this program in elementary and i loved this, so i decided to write an article in the most popular fórum of latin america recommending it for people you know... because it was very useful to me. The problem is, somehow meson is just not working here, and for recommend the app in a General Linux fórum, i need to show people how to install it in at least one great distribution, the PPA of Felipe Escoto is not working for Wallpaperize, and the meson is not working... but i have to say, im not experienced in compile programs. So, could you guys check if everything is right with the README file?

Thank you!

**Comment by RLFontan** [comment]
Erros like: 

"No such file or directory" when i run "meson build" inside the package file.

So i tried to: mkdir build > meson build = worked. But then a tried to do the mesonconf and just not worked, saying the the build directory "not seem as a build directory".

Thats all, then i just runned out of time to research a solution.

**Comment by Philip-Scott** [comment]
where are you trying to run meson build at? Because it's working properly for me :thinking: 

Here's the log:

```
~ $ git clone git@github.com:Philip-Scott/wallpaperize.git
Cloning into 'wallpaperize'...
remote: Counting objects: 99, done.
remote: Total 99 (delta 0), reused 0 (delta 0), pack-reused 99
Receiving objects: 100% (99/99), 941.63 KiB | 1.51 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Checking connectivity... done.
~ $ cd wallpaperize/
~/wallpaperize [master] $ meson build
The Meson build system
Version: 0.41.1
Source dir: /home/felipe/wallpaperize
Build dir: /home/felipe/wallpaperize/build
Build type: native build
Project name: com.github.philip-scott.wallpaperize
Native c compiler: cc (gcc 5.4.0)
Native vala compiler: valac (valac 0.34.9)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.48.2
Native dependency gobject-2.0 found: YES 2.48.2
Native dependency gtk+-3.0 found: YES 3.18.9
Native dependency granite found: YES 0.4.1
Build targets in project: 1
~/wallpaperize [master] $ cd build/
~/wallpaperize/build [master] $ mesonconf -Dprefix=/usr
~/wallpaperize/build [master] $ ninja
[0/1] Regenerating build files.
The Meson build system
Version: 0.41.1
Source dir: /home/felipe/wallpaperize
Build dir: /home/felipe/wallpaperize/build
Build type: native build
Project name: com.github.philip-scott.wallpaperize
Native c compiler: cc (gcc 5.4.0)
Native vala compiler: valac (valac 0.34.9)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring config.h using configuration
Build targets in project: 1
[5/5] Linking target com.github.philip-scott.wallpaperize.
~/wallpaperize/build [master] $ 
```

**Comment by RLFontan** [comment]
I just failed right here. Can't recommend this way of installing to normal users like me. I already have the post for the forum totally done, the problem is the part that i show the guys how they can get the app. In Elementary its very easy, but in any other big distribution its just not soft to install.

I have an ideia right here. If i use the Elementary OS PPA to install the App Center on others Ubuntu based distribution, when i open it, the Wallpaperize will be there on the App Center? Because if it works the problem is solved. 

In last case, no problem, i will just publish the article and keep other users updated on the Wallpaperize package portability news. But it will be sad :(. 

Thank you! And Thank also for develop this app! Its very cool!

**Comment by Philip-Scott** [comment]
Give me until the end of the week, and I can added it to my PPA :) but try with the commands again, and post the output. You might be missing some dependencies
