### ISSUE TITLE
Build with meson fails

### ISSUE THREAD

**Issue by kuriot** [Philip-Scott/wallpaperize#15]
Hello.

After git cloning and making build directory (if not make it meson says that there is no build directory) I try to make meson build, but it gives an error:

```
~/.local/src/wallpaperize$ meson build
The Meson build system
Version: 0.35.0
Source dir: /home/kuriot/.local/src/wallpaperize
Build dir: /home/kuriot/.local/src/wallpaperize/build
Build type: native build

Meson encountered an error:
Arguments must be strings.
```

**Comment by Philip-Scott** [comment]
I have version `0.41.2` of meson. On which distro are you trying to install it?

**Comment by Philip-Scott** [comment]
duplicate of #14
