### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by IDOHAVENOT** [Philip-Scott/wallpaperize#25]
pop@pos:~/Downloads/wallpaperize/build$ meson configure -Dprefix=/usr
pop@pos:~/Downloads/wallpaperize/build$ ninja
[0/1] Regenerating build files.
The Meson build system
Version: 0.53.2
Source dir: /home/pop/Downloads/wallpaperize
Build dir: /home/pop/Downloads/wallpaperize/build
Build type: native build
Project name: com.github.philip-scott.wallpaperize
Project version: 0.2.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.48.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h using configuration
Dependency glib-2.0 found: YES 2.64.2 (cached)
Dependency gobject-2.0 found: YES 2.64.2 (cached)
Dependency gtk+-3.0 found: YES 3.24.18 (cached)
Dependency granite found: YES 5.3.0 (cached)
Build targets in project: 1

Found ninja-1.10.0 at /usr/bin/ninja
[1/5] Compiling Vala source ../src/App.../Wallpaperize.vala ../src/Window.vala.
FAILED: com.github.philip-scott.wallpaperize@exe/src/Application.c com.github.philip-scott.wallpaperize@exe/src/Wallpaperize.c com.github.philip-scott.wallpaperize@exe/src/Window.c 
valac -C --debug --debug --pkg granite --pkg gtk+-3.0 --pkg gobject-2.0 --pkg glib-2.0 --color=always --directory com.github.philip-scott.wallpaperize@exe --basedir ../ ../src/Application.vala ../src/Wallpaperize.vala ../src/Window.vala
../src/Wallpaperize.vala:27.31-27.56: warning: `Gdk.Screen.get_primary_monitor' has been deprecated since 3.22
../src/Wallpaperize.vala:29.9-29.35: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
../src/Wallpaperize.vala:31.29-31.59: warning: `Gdk.Screen.get_monitor_scale_factor' has been deprecated since 3.22
../src/Window.vala:48.3-48.19: error: Property `Wallpaperize.Window.file' with custom `get' accessor and/or `set' mutator cannot have `default' value
  public File? file {
  ^^^^^^^^^^^^^^^^^
../src/Application.vala:31.9-31.17: warning: `Granite.Application.app_years' has been deprecated since 0.4.2. Use 
../src/Application.vala:36.9-36.16: warning: `Granite.Application.app_icon' has been deprecated since 0.4.2. Use 
../src/Application.vala:37.9-37.16: warning: `Granite.Application.main_url' has been deprecated since 0.4.2. Use 
../src/Application.vala:38.9-38.15: warning: `Granite.Application.bug_url' has been deprecated since 0.4.2. Use 
../src/Application.vala:39.9-39.16: warning: `Granite.Application.help_url' has been deprecated since 0.4.2. Use 
../src/Application.vala:40.9-40.21: warning: `Granite.Application.translate_url' has been deprecated since 0.4.2. Use 
../src/Application.vala:41.9-41.21: warning: `Granite.Application.about_authors' has been deprecated since 0.4.2. Use 
../src/Application.vala:42.9-42.25: warning: `Granite.Application.about_translators' has been deprecated since 0.4.2. Use 
../src/Application.vala:44.9-44.26: warning: `Granite.Application.about_license_type' has been deprecated since 0.4.2. Use 
Compilation failed: 1 error(s), 12 warning(s)
ninja: build stopped: subcommand failed.

**Comment by ryonakano** [comment]
#19 should fix this
