### ISSUE TITLE
Doesn't detect HiDPI

### ISSUE THREAD

**Issue by danirabbit** [Philip-Scott/wallpaperize#5]
Wallpaperize suggests a resolution of 1600 x 900, but since I'm running @2x, it should be 3200 x 1800

**Comment by soapyham** [comment]
Daniel can you test with this commit https://github.com/Philip-Scott/wallpaperize/commit/6959dadf29eb34032bb26a416c29a3665a646fc4?

**Comment by danirabbit** [comment]
Yep, seems fixed here :)
